language: python
python: 
  - "3.6"

addons:
  postgresql: "9.6"

install: 
  - pip install pipenv
  - pipenv install
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source='apps' manage.py test
  - flake8
  - coverage report -m


after_success:
  - coveralls
